### ISSUE TITLE
Add-on stopped working

### ISSUE THREAD

**Issue by BoredLama** [rleroi/stremio-anime#9]
Seems the API has been removed or changed

**Comment by rleroi** [comment]
The KissAnime API is behind a CloudFlare proxy, so sometimes the server IP gets flagged and has to fill in a captcha. That's when the add-on is unavailable. Also the there seems to be a misconfiguration in PM2 since the app isn't automatically restarting on a crash.

Right now it is working again, do you know if for instance now.sh is a good alternative? You seem to be using it, is the free version enough for the amount of requests you're getting? And does it have multiple IP addresses?

**Comment by BoredLama** [comment]
there's no request limit that i know of on now.sh free hosting, none of my add-ons went down randomly (like they do on heroku, for example)

but if the IP getting flagged is the issue here, then it will get flagged regardless of the hosting you use, and the IP of now.sh / heroku might already be flagged by cloudflare.

you should use the newest SDK and set `cacheMaxAge` on the add-on responses to cache on the user side too, and maybe even set up cloudflare yourself to use cloudflare's cdn too.. this might drastically reduce the number of requests your making (especially if you set a high cache time on search requests, but i wouldn't recommend a higher cache then 5 min for stream responses, as those usually expire fast)

you could also use proxies (simple, free cors proxies will also work), look here:
https://github.com/BoredLama/stremio-top-seeded-zooqle/blob/master/index.js#L6

but again, no matter where you host it, no matter if you use proxies or not, it will still go down if you don't do caching well

**Comment by BoredLama** [comment]
from the stremio add-on sdk docs:
- [Deploying to Now.sh with CloudFlare](https://github.com/Stremio/stremio-addon-sdk/blob/master/docs/deploying/now.md)
- [Deploying to Glitch with CloudFlare](https://github.com/Stremio/stremio-addon-sdk/blob/master/docs/deploying/glitch.md)

heroku can also be used, but there's no guide for it and you need to do cc verification for them to keep your app alive through the month.

now.sh doesn't have a known limit that i know of, alternatively glitch has a limit of 4000 requests per hour, and sleeps your app after 5 mins, there's a hack in the guide that stops it from letting your app go to sleep.

both guides cover how to get a free domain for a year, setting things up with cloudflare, etc

then if you set `cacheMaxAge` in the responses too, it should reduce your requests dramatically.. and cost you nothing..

**Comment by BoredLama** [comment]
you might want to change your add-on id when you publish it to stremio from a .ga domain, otherwise the add-on catalog might consider it a duplicate because of the same id

**Comment by rleroi** [comment]
thanks, i did.

Also, I read on the now.sh website that free users only have 1000 requests a day? i hope thats enough since the old anime add-on had 6million requests a month and increasing.
I didn't understand why cloudflare didnt cache my add-on before, but thanks to this guide i found out it doesn't cache JSON by default, so that should help. hopefully the 1000 requests a day will do!

**Comment by rleroi** [comment]
im not sure what now.sh means with the 1000 requests or invocations a day because im getting more requests and it still seems to work

**Comment by BoredLama** [comment]
I haven't experienced any limits to now.sh yet..
